### ISSUE TITLE
Adding proper documentation for the new version of App

### ISSUE THREAD

**Issue by Ananyaiitbhilai** [OpenLake/Knowlege-Sharing-Platform#20]
Adding information about new features and enhacements.

**Comment by lakshyaTomar** [comment]
I would like to work on this issue. @Ananyaiitbhilai @AnshumanDhiman

**Comment by AnshumanDhiman** [comment]
go ahead @lakshyaTomar

**Comment by AnshumanDhiman** [comment]
Done via PR #28 
Closing this issue
